#!/bin/bash
#--------------------------------------------------------------------------
# 概要：
#   ApacheLogをTailし、結果をKafkaBrokerに送信するKakfaProducerプロセス終了コマンド
#
# 使用方法：
#   stop_kafka_producer
#--------------------------------------------------------------------------

#-----------
# 変数初期化
#-----------
USAGE_MESSAGE='Usage : stop_kafka_producer'

SCRIPT_PATH=`readlink -f $0`
SCRIPT_DIR=`dirname $SCRIPT_PATH`

#-----------
# 関数定義
#-----------
#+ ----------------------------------------------------
#+  指定引数の数が不正なパターンをUsageメッセージで除外
#+ ----------------------------------------------------
function checkArgNum {
  # 引数が指定された場合はエラーとする
  if [ $# -ne 0 ]
  then
    echo -e "${USAGE_MESSAGE}"
    exit 1
  fi
}


#-----------
# メイン処理
#-----------
# 引数チェック
checkArgNum $@

echo KakfaProducerを停止します...

pkill -f Dkafka_producer 
